### ISSUE TITLE
Custom jwtDecoder not configured

### ISSUE THREAD

**Issue by ktsowes** [auth0-samples/auth0-spring-security5-api-sample#21]
Hi

I think the custom jwtDecoder decoder is not configured.

Shouldn't it be configured in SecurityConfig.java like this?

        http.authorizeRequests()
                .mvcMatchers("/api/public").permitAll()
                .mvcMatchers("/api/private*").authenticated()
                .and().cors()
                .and().oauth2ResourceServer()
                .jwt(jwt -> jwt.decoder(jwtDecoder()));
        return http.build();

**Comment by jimmyjames** [comment]
Hi @ktsowes, I think the `jwtDecoder` bean definition should configure it, but I'll double check to make sure. Thanks!

**Comment by jimmyjames** [comment]
I confirmed that the custom jwtDecoder is indeed configured and used in the sample. If you debug the app, you can see that the bean gets configured and then the `AudienceValidator` is called as expected.
