### ISSUE TITLE
Does not work with spring > 3

### ISSUE THREAD

**Issue by magwas** [auth0-samples/auth0-spring-security5-api-sample#24]
I had a working setup.

I upgraded spring-boot-starter-parent from 2.7.1 to 3.0.2.
Because of that some imports changed from javax.servlet to jacarta.servlet
In the SecurityFilterChain the `authz.antMatchers(HttpMethod.GET, "/api/v1/hero")` call changed to
`authz.requestMatchers(HttpMethod.GET, "/api/v1/hero")`

Now I get 404 for both get and post for the url. (Wait, before that POST to that url was working as well, and it did need authentication and csrf... So there is something not really right in the config...)

The diff between the nonworking and working setup is here: https://gist.github.com/magwas/53d4cfcb7769d9f7f5ef5978fa121bf9

My full SecurityConfig (new version):
```
package com.kodekonveyor;

import org.slf4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.http.HttpMethod;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.csrf.CookieCsrfTokenRepository;

import com.kodekonveyor.annotations.InterfaceClass;

@InterfaceClass
@EnableWebSecurity
public class SecurityConfig {

	@Value("${auth0.audience}")
	private String audience;

	@Value("${spring.security.oauth2.resourceserver.jwt.issuer-uri}")
	private String issuer;

	@Autowired
	Logger logger;

	@Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
		http
				.authorizeHttpRequests(
						authz -> authz
								.requestMatchers(HttpMethod.GET, "/api/v1/hero")
								.hasAuthority("SCOPE_read:current_user")
								.anyRequest().permitAll())
				.oauth2ResourceServer(oauth2 -> oauth2.jwt())
				.csrf()
				.csrfTokenRepository(
						CookieCsrfTokenRepository.withHttpOnlyFalse());

		return http.build();

	}
}
```

**Comment by magwas** [comment]
I have moved the bean to my SpringConfig class (having annotations `@EnableWebSecurity` `@SpringBootApplication` and
`@ServletComponentScan`.

The bean currently looks like below. It is working.
Correctly denies access for POST requests without Authorization as well, which I do not understand.

```
	@Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
		http
				.authorizeHttpRequests(
						authz -> authz
						
								.requestMatchers(HttpMethod.GET, "/api/v1/hero")
								.hasAuthority("SCOPE_read:current_user")
								.anyRequest()
								.permitAll())
				.oauth2ResourceServer(oauth2 -> oauth2.jwt())
				.csrf()
				.csrfTokenRepository(
						CookieCsrfTokenRepository.withHttpOnlyFalse())
				;

		return http.build();

	}
```

**Comment by jimmyjames** [comment]
👋 hi @magwas, thanks for raising. I created #25 to consolidate the issues/questions around Spring Boot 3 and Spring Security 6, along with my findings. Check out that issue and my findings, and let's move the conversation there (feel free to share any additional findings or other issues you've encountered there). Thanks!
