### ISSUE TITLE
Built-in audience check

### ISSUE THREAD

**Issue by jaredtbates** [auth0-samples/auth0-spring-security5-api-sample#27]
Hi there! Are there any benefits to using a custom `AudienceValidator` vs using the built-in property?

https://github.com/spring-projects/spring-boot/pull/29084

Just wanted to check before moving forward with our integration - I don't think there is a difference functionally but wanted to check the Auth0 team's advice. Thank you!

**Comment by jimmyjames** [comment]
Hey @jaredtbates, thanks for providing that info! If Spring now has support for audience validation, there's no need for a custom validator 👍
