### ISSUE TITLE
How to retrieve userId with reactive spring security (webflux)?

### ISSUE THREAD

**Issue by crzyjcky** [auth0-samples/auth0-spring-security5-api-sample#7]
For protected api, how do I able to retrieve logged-in userId? Can you share me sone example code on how to do that? Thanks.

I tried with the code below, but I always receive null.
```
Object p = ReactiveSecurityContextHolder.getContext()
        .map(SecurityContext::getAuthentication)
        .map(Authentication::getPrincipal).block();
```

https://community.auth0.com/t/how-to-retrieve-userid-with-reactive-spring-security/47721

**Comment by jimmyjames** [comment]
Hi @crzyjcky, this sample only demonstrates validating the Auth0-issued access token (JWT) when attempting to access APIs (authorization), and for simplicity the guidance here is to obtain a token for your API through the API settings in the Management Dashboard. User information would be present in an [ID token](https://auth0.com/docs/tokens/id-tokens/id-token-structure) that gets issued when logging in (authentication). You can see an example of that in our [Spring Boot Login Sample](https://github.com/auth0-samples/auth0-spring-boot-login-samples).

**Comment by wrightak** [comment]
@jimmyjames Thanks for answering this question. Like the OP, I need to have some kind of identifier for the user that I can store in the database that is connected to my API. To make sure I am understanding correctly, is the typical flow something like this?

User authenticates (in my case through an iOS app)
Successful authentication gives an access token and an id token
Use the access token to authenticate with this Spring API. Get the "sub" field in the id token and send that as well (maybe in the request body or in another header?)
Use this "sub" field as an identifier for the user that can be used in a "user id" column in a database

Does this sound right?

**Comment by wrightak** [comment]
For anyone else reading this, I realized that the access token contains the user_id in the subject claim, so no need to get it from the id token.

Something like this will give you that in the controller: 

```
    @GetMapping(value = ["/private"])
    fun privateEndpoint(principal: Principal): Message {
        return Message("All good. You can see this because you are Authenticated. Principal name is ${principal.name}")
    }
```
