### ISSUE TITLE
Authentication passing even when token is not passed, if previously passed

### ISSUE THREAD

**Issue by shagunbandi** [auth0-samples/auth0-spring-security5-api-sample#8]
If I pass the token and it, authenticates, next time It's not asking for token and authenticating directly
<img width="1792" alt="Screenshot 2020-09-12 at 11 29 28 AM" src="https://user-images.githubusercontent.com/18301341/92988672-4926e880-f4eb-11ea-85ed-aadb8d71e9b1.png">
<img width="1792" alt="Screenshot 2020-09-12 at 11 29 18 AM" src="https://user-images.githubusercontent.com/18301341/92988675-4fb56000-f4eb-11ea-970f-18c5d8cdb04e.png">

**Comment by jimmyjames** [comment]
Is this reproducible with other REST clients (e.g., cURL or httpie), or could this be something specific with Postman?

**Comment by Z-EMB** [comment]
Ran into the same thing (on springboot 2.3.1)

JSESSION cookie is created on 200, and subsequent requests do not need Bearer token. One way to fix this is `http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS).and()...`

"could this be something specific with Postman?" yes, postman saves the cookie and passes it on next request

**Comment by jimmyjames** [comment]
Closing this as it appears to be an issue with the specific REST client.
